EMAIL_PASSWORD = "Fill this field"
EMAIL_ADDRESS = "Fill this field"
IP_BRIDGE = "Fill this field"
EMAIL_SUBJECT = "Philips HUE"
USERNAME = 'Your username for the bridge registration'
START_BRIGHTNESS = 254
START_COLORTEMP = 369
START_SATURATION = 144
OPTIMAL_XY = [0.509, 0.4149]
